version: '3.5'
networks:
  ktor-network:
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/date:/var/lib/postgresql/data
    networks:
      - ktor-network
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]

  ktor_server:
    build:
      context: .
    container_name: my-ktor-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ktor-network